name: amaanah-examination-system

services:
- name: web
  source_dir: .
  build_command: apt-get update && apt-get install -y chromium-browser && npm ci && node build.mjs
  run_command: NODE_ENV=production node dist/server/index.js
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: SESSION_SECRET
    value: ${SESSION_SECRET}
  - key: DATABASE_URL
    value: ${DATABASE_URL}
