name: amaanah-examination-system

services:
- name: web
  source_dir: .
  build_command: node build.mjs
  run_command: NODE_ENV=production node dist/server/index.cjs
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
